apiVersion: apps/v1
kind: Deployment
metadata:
  name: customers-db-deployment
  labels:
    app: customers-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customers-db
  template:
    metadata:
      labels:
        app: customers-db
    spec:
      containers:
        - name: customers-db
          image: mongodb/mongodb-community-server:7.0.7-ubi8
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: USER
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: customers-db-service
spec:
  selector:
    app: customers-db
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  type: ClusterIP